### PR TITLE
Update clj-time, fix resulting deprecation warnings

### PR DESCRIPTION
**Pull request by j0ni**

### CODE REVIEW

**Comment by startling** [comment]
LGTM

**Comment by gordonsyme** [comment]
Thank you, thank you, thank you!

Is there a corresponding update to `circleci/circle/project.clj`? (I'm only catching up on all last weeks PRs now)

**Comment by marcomorain** [comment]
I updated the project.clj – Joni fixed a bunch of deprecation warning that
I missed. Thanks for that Joni.

**Comment by gordonsyme** [comment]
Ah, I meant for the mongofinil dependency

**Pull request merged**
